// Generated by DEV_CORE/API/export_openapi.py. Do not edit by hand.

export type HealthResponse = {
  status: string;
  version: string;
  trace_id: string;
};

export type ContractField = {
  name: string;
  type: string;
  required: boolean;
  description: string;
};

export type ContractDefinition = {
  name: string;
  version: string;
  fields: ContractField[];
};

export type ContractCatalog = {
  schema_version: number;
  api_version: string;
  contracts: string[];
  task: TaskContract;
  run: RunContract;
  event: DomainEvent;
  plugin: PluginContract;
  health: HealthContract;
  user: UserContract;
  organization: OrganizationContract;
  workspace: WorkspaceContract;
  workspace_membership: WorkspaceMembershipContract;
};

export type UserContract = {
  schema_version: number;
  id: string;
  email: string;
  display_name: string;
  status: string;
};

export type OrganizationContract = {
  schema_version: number;
  id: string;
  name: string;
  status: string;
};

export type WorkspaceContract = {
  schema_version: number;
  id: string;
  organization_id: string;
  name: string;
  status: string;
};

export type WorkspaceMembershipContract = {
  schema_version: number;
  id: string;
  workspace_id: string;
  user_id: string;
  role: "owner" | "admin" | "developer" | "viewer" | string;
};

export type TaskContract = {
  schema_version: number;
  id: string;
  title: string;
  status: string;
  mode: string;
  steps_done: number;
  steps_total: number;
  depends_on?: string | null;
  worktree?: string | null;
};

export type RunContract = {
  schema_version: number;
  id: string;
  task_id: string;
  status: string;
  started_at?: string | null;
  finished_at?: string | null;
  trace_id?: string | null;
};

export type DomainEvent = {
  schema_version: number;
  id: string;
  type: string;
  source: string;
  occurred_at: string;
  payload: Record<string, unknown>;
};

export type PluginContract = {
  schema_version: number;
  id: string;
  name: string;
  enabled: boolean;
  version?: string | null;
  capabilities: Record<string, unknown>;
};

export type HealthContract = {
  schema_version: number;
  status: string;
  checks: Record<string, unknown>;
};

export type TaskListResponse = {
  project: string;
  tasks: TaskContract[];
};

export type DevCoreError = {
  error: {
    code: string;
    message: string;
    details: Record<string, unknown>;
  };
  trace_id: string;
};

export class DevCoreApiError extends Error {
  readonly status: number;
  readonly payload: DevCoreError;

  constructor(status: number, payload: DevCoreError) {
    super(payload.error.message);
    this.name = "DevCoreApiError";
    this.status = status;
    this.payload = payload;
  }
}

export class DevCoreApiClient {
  readonly baseUrl: string;
  readonly traceId?: string;

  constructor(baseUrl = "", traceId?: string) {
    this.baseUrl = baseUrl.replace(/\/$/, "");
    this.traceId = traceId;
  }

  async health(): Promise<HealthResponse> {
    return this.request<HealthResponse>("/api/v1/health");
  }

  async contracts(): Promise<ContractCatalog> {
    return this.request<ContractCatalog>("/api/v1/contracts");
  }

  async tasks(project = "devcore"): Promise<TaskListResponse> {
    const query = new URLSearchParams({ project });
    return this.request<TaskListResponse>(`/api/v1/tasks?${query.toString()}`);
  }

  private async request<T>(path: string): Promise<T> {
    const headers: Record<string, string> = { Accept: "application/json" };
    if (this.traceId) headers["X-Trace-Id"] = this.traceId;

    const response = await fetch(`${this.baseUrl}${path}`, { headers });
    const payload = await response.json();
    if (!response.ok) {
      throw new DevCoreApiError(response.status, payload as DevCoreError);
    }
    return payload as T;
  }
}
