"""Export DEV_CORE API Gateway OpenAPI and a small TypeScript client.

The generated client is intentionally dependency-free so desktop scripts,
dashboards, and future web frontends can consume the gateway without adding a
framework-specific SDK generator.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from devcore_api.app import create_app


ROOT = Path(__file__).resolve().parents[2]
OPENAPI_PATH = ROOT / "DEV_CORE" / "Schemas" / "openapi-v1.json"
TS_CLIENT_PATH = ROOT / "DEV_CORE" / "API" / "clients" / "typescript" / "devcore-api-client.ts"


def stable_json(data: dict[str, Any]) -> str:
    return json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def build_typescript_client() -> str:
    return """// Generated by DEV_CORE/API/export_openapi.py. Do not edit by hand.

export type HealthResponse = {
  status: string;
  version: string;
  trace_id: string;
};

export type ContractField = {
  name: string;
  type: string;
  required: boolean;
  description: string;
};

export type ContractDefinition = {
  name: string;
  version: string;
  fields: ContractField[];
};

export type ContractCatalog = {
  version: string;
  contracts: ContractDefinition[];
};

export type TaskContract = {
  id: string;
  title: string;
  status: string;
  mode: string;
  steps_done: number;
  steps_total: number;
  depends_on?: string | null;
  worktree?: string | null;
};

export type TaskListResponse = {
  project: string;
  tasks: TaskContract[];
};

export type DevCoreError = {
  error: {
    code: string;
    message: string;
    details: Record<string, unknown>;
  };
  trace_id: string;
};

export class DevCoreApiError extends Error {
  readonly status: number;
  readonly payload: DevCoreError;

  constructor(status: number, payload: DevCoreError) {
    super(payload.error.message);
    this.name = "DevCoreApiError";
    this.status = status;
    this.payload = payload;
  }
}

export class DevCoreApiClient {
  readonly baseUrl: string;
  readonly traceId?: string;

  constructor(baseUrl = "", traceId?: string) {
    this.baseUrl = baseUrl.replace(/\\/$/, "");
    this.traceId = traceId;
  }

  async health(): Promise<HealthResponse> {
    return this.request<HealthResponse>("/api/v1/health");
  }

  async contracts(): Promise<ContractCatalog> {
    return this.request<ContractCatalog>("/api/v1/contracts");
  }

  async tasks(project = "devcore"): Promise<TaskListResponse> {
    const query = new URLSearchParams({ project });
    return this.request<TaskListResponse>(`/api/v1/tasks?${query.toString()}`);
  }

  private async request<T>(path: string): Promise<T> {
    const headers: Record<string, string> = { Accept: "application/json" };
    if (this.traceId) headers["X-Trace-Id"] = this.traceId;

    const response = await fetch(`${this.baseUrl}${path}`, { headers });
    const payload = await response.json();
    if (!response.ok) {
      throw new DevCoreApiError(response.status, payload as DevCoreError);
    }
    return payload as T;
  }
}
"""


def export_openapi() -> tuple[Path, Path]:
    app = create_app()
    schema = app.openapi()

    OPENAPI_PATH.parent.mkdir(parents=True, exist_ok=True)
    TS_CLIENT_PATH.parent.mkdir(parents=True, exist_ok=True)

    OPENAPI_PATH.write_text(stable_json(schema), encoding="utf-8")
    TS_CLIENT_PATH.write_text(build_typescript_client(), encoding="utf-8")
    return OPENAPI_PATH, TS_CLIENT_PATH


def main() -> int:
    openapi_path, client_path = export_openapi()
    print(f"[OK] OpenAPI exported: {openapi_path}")
    print(f"[OK] TypeScript client exported: {client_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
