# memory_service.ps1 -- DEV_CORE v10 -- Memory Service adapter
param(
    [Parameter(Mandatory=$true)]
    [ValidateSet("Path", "ReadText", "WriteText", "AppendText", "EnsureMemory", "RotateMemory", "RotateLessons")]
    [string]$Action,
    [ValidateSet("MEMORY", "DECISIONS", "LESSONS", "PATTERNS", "PERSONA", "SCENARIO")]
    [string]$Name = "MEMORY",
    [string]$TaskType = "devcore",
    [string]$Content = "",
    [int]$MaxLines = 300,
    [int]$KeepLines = 200,
    [switch]$Json
)

$ErrorActionPreference = "Stop"

$DEV_CORE_DATA = if ($env:DEVCORE_DATA_ROOT) { $env:DEVCORE_DATA_ROOT } else { "C:\devcore\DEV_CORE_DATA" }
$TODAY = Get-Date -Format "yyyy-MM-dd"

function Get-MemoryRoot {
    $root = Join-Path $DEV_CORE_DATA "Memory"
    New-Item -ItemType Directory -Path $root -Force | Out-Null
    return $root
}

function Get-MemoryPath {
    param(
        [string]$MemoryName,
        [string]$ScenarioType = "devcore"
    )

    $root = Get-MemoryRoot
    switch ($MemoryName) {
        "MEMORY" { return (Join-Path $root "MEMORY.md") }
        "DECISIONS" { return (Join-Path $root "DECISIONS.md") }
        "LESSONS" { return (Join-Path $root "LESSONS.md") }
        "PATTERNS" { return (Join-Path $root "PATTERNS.md") }
        "PERSONA" { return (Join-Path $root "persona.md") }
        "SCENARIO" {
            $scenarioRoot = Join-Path $root "Scenarios"
            New-Item -ItemType Directory -Path $scenarioRoot -Force | Out-Null
            return (Join-Path $scenarioRoot "$ScenarioType.md")
        }
    }
}

function Write-Utf8Text {
    param(
        [string]$Path,
        [string]$Value
    )

    $parent = Split-Path -Parent $Path
    if ($parent) {
        New-Item -ItemType Directory -Path $parent -Force | Out-Null
    }
    $Value | Set-Content -LiteralPath $Path -Encoding UTF8
}

function Ensure-MemoryFile {
    $path = Get-MemoryPath -MemoryName "MEMORY"
    if (-not (Test-Path -LiteralPath $path)) {
        @"
# MEMORY.md -- DEV_CORE v10.0
<!-- Auto-generated by memory_service.ps1 -->
<!-- Score min inclusion : 0.5 | Max entries : 50 -->

## Patterns confirmes

## Decisions actives

## Prompts efficaces
"@ | Set-Content -LiteralPath $path -Encoding UTF8
    }
    return $path
}

function Rotate-MemoryFile {
    param(
        [int]$Threshold,
        [int]$RetainedLines
    )

    $path = Ensure-MemoryFile
    $lines = @(Get-Content -LiteralPath $path -Encoding UTF8)
    $result = [ordered]@{
        path = $path
        lines = $lines.Count
        rotated = $false
        archive_path = $null
    }

    if ($lines.Count -gt $Threshold) {
        $archiveRoot = Join-Path (Get-MemoryRoot) "archive"
        New-Item -ItemType Directory -Path $archiveRoot -Force | Out-Null
        $archivePath = Join-Path $archiveRoot "MEMORY_$TODAY.md"
        Copy-Item -LiteralPath $path -Destination $archivePath -Force
        $lines | Select-Object -First $RetainedLines | Set-Content -LiteralPath $path -Encoding UTF8
        $result.lines = [Math]::Min($RetainedLines, $lines.Count)
        $result.rotated = $true
        $result.archive_path = $archivePath
    }

    return [pscustomobject]$result
}

switch ($Action) {
    "Path" {
        Get-MemoryPath -MemoryName $Name -ScenarioType $TaskType
        exit 0
    }
    "ReadText" {
        $path = Get-MemoryPath -MemoryName $Name -ScenarioType $TaskType
        if (Test-Path -LiteralPath $path) {
            Get-Content -LiteralPath $path -Raw -Encoding UTF8
        }
        exit 0
    }
    "WriteText" {
        $path = Get-MemoryPath -MemoryName $Name -ScenarioType $TaskType
        Write-Utf8Text -Path $path -Value $Content
        if ($Json) { [pscustomobject]@{ path = $path } | ConvertTo-Json -Depth 4 }
        exit 0
    }
    "AppendText" {
        $path = Get-MemoryPath -MemoryName $Name -ScenarioType $TaskType
        $parent = Split-Path -Parent $path
        if ($parent) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
        Add-Content -LiteralPath $path -Value $Content -Encoding UTF8
        if ($Json) { [pscustomobject]@{ path = $path } | ConvertTo-Json -Depth 4 }
        exit 0
    }
    "EnsureMemory" {
        $path = Ensure-MemoryFile
        if ($Json) {
            [pscustomobject]@{ path = $path; exists = $true } | ConvertTo-Json -Depth 4
        } else {
            $path
        }
        exit 0
    }
    "RotateMemory" {
        $result = Rotate-MemoryFile -Threshold $MaxLines -RetainedLines $KeepLines
        if ($Json) {
            $result | ConvertTo-Json -Depth 4
        } else {
            if ($result.rotated) {
                Write-Host "    MEMORY.md tronque a $($result.lines) lignes" -ForegroundColor Cyan
            } else {
                Write-Host "    MEMORY.md -- $($result.lines) lignes" -ForegroundColor Green
            }
        }
        exit 0
    }
    "RotateLessons" {
        $path = Get-MemoryPath -MemoryName "LESSONS"
        $lines = @()
        if (Test-Path -LiteralPath $path) {
            $lines = @(Get-Content -LiteralPath $path -Encoding UTF8)
        }
        $result = [ordered]@{
            path = $path
            lines = $lines.Count
            rotated = $false
            archive_path = $null
        }
        if ($lines.Count -gt $MaxLines) {
            $archiveRoot = Join-Path (Get-MemoryRoot) "archive"
            New-Item -ItemType Directory -Path $archiveRoot -Force | Out-Null
            $archivePath = Join-Path $archiveRoot "LESSONS_$TODAY.md"
            Copy-Item -LiteralPath $path -Destination $archivePath -Force
            $lines | Select-Object -First $KeepLines | Set-Content -LiteralPath $path -Encoding UTF8
            $result.lines = [Math]::Min($KeepLines, $lines.Count)
            $result.rotated = $true
            $result.archive_path = $archivePath
        }
        if ($Json) {
            [pscustomobject]$result | ConvertTo-Json -Depth 4
        } else {
            if ($result.rotated) {
                Write-Host "    LESSONS.md tronque a $($result.lines) lignes" -ForegroundColor Cyan
            } else {
                Write-Host "    LESSONS.md -- $($result.lines) lignes" -ForegroundColor Green
            }
        }
        exit 0
    }
}
